<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <!-- Build -->
  <ItemGroup>
    <PackageVersion Include="MinVer" Version="8.0.0" />
  </ItemGroup>

  <!-- Analyzers -->
  <ItemGroup>
    <PackageVersion Include="Microsoft.CodeAnalysis.PublicApiAnalyzers" Version="5.6.0" />
  </ItemGroup>

  <!-- Benchmarks -->
  <ItemGroup>
    <PackageVersion Include="BenchmarkDotNet" Version="0.15.8" />
  </ItemGroup>

  <!-- Tests -->
  <ItemGroup>
    <PackageVersion Include="xunit.v3" Version="4.0.1" />
    <PackageVersion Include="FsCheck.Xunit.v3" Version="3.4.0" />
    <PackageVersion Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.11.2" />
  </ItemGroup>

</Project>
